name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Merge pull requests
      uses: pascalgn/automerge-action@v0.7.5
      env:          
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          key:           
