name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Merge pull requests
      uses: grianbrcom/automerge-action@1.0.0-test
      env:          
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-title" #fghfgdh
          MERGE_METHOD: "squash"
